# Generated by Django 4.2.7 on 2024-08-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_entrenamiento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='progreso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, default='Desconocida', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, default='Desconocida', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default='Desconocida', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='semana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tipo_entrenamiento',
            field=models.CharField(blank=True, default='Default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece el usuario.', related_name='usuarios_user_set_custom', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para el usuario.', related_name='usuarios_user_permissions_set_custom', to='auth.permission'),
        ),
    ]
