# Generated by Django 4.2.7 on 2024-08-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_entrenamiento_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
    ]
