# Generated by Django 4.2.7 on 2024-08-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alumno_gimnasio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('sexo', models.CharField(max_length=10)),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('perimetro_cefalico', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LactanteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('peso_actual', models.FloatField()),
                ('peso_pregestacional', models.FloatField()),
                ('imc_actual', models.CharField(max_length=50)),
                ('dias_post_parto', models.IntegerField()),
                ('retencion_post_parto', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GestanteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('semana_gestacion', models.IntegerField()),
                ('peso_actual', models.FloatField()),
                ('peso_pregestacional', models.FloatField()),
                ('imc_pregestacional', models.CharField(max_length=50)),
                ('imc_gestacional', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
