# Generated by Django 4.2.7 on 2024-08-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_ninoinfo_lactanteinfo_gestanteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lactanteinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='estatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='imc_gestacional',
            field=models.CharField(default='No calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='imc_pregestacional',
            field=models.CharField(default='No calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='peso_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='peso_pregestacional',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='semana_gestacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='dias_post_parto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='estatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='imc_actual',
            field=models.CharField(default='No calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='peso_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='peso_pregestacional',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='retencion_post_parto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='estatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='perimetro_cefalico',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='sexo',
            field=models.CharField(default='No especificado', max_length=10),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='talla',
            field=models.FloatField(default=0.0),
        ),
    ]
