# Generated by Django 4.2.7 on 2024-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_gestanteinfo_user_remove_lactanteinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestanteinfo',
            name='imc_pregestacional_cat',
            field=models.CharField(default='No calculado', max_length=50),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='imc_cat',
            field=models.CharField(default='No calculado', max_length=50),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='imc_gestacional',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gestanteinfo',
            name='imc_pregestacional',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='imc_actual',
            field=models.FloatField(default=0.0),
        ),
    ]
