# Generated by Django 4.2.7 on 2024-09-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_gestanteinfo_imc_pregestacional_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinoSanoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacion', models.CharField(default='No Aplica', max_length=50)),
                ('pt', models.CharField(default='', max_length=20)),
                ('te', models.CharField(default='', max_length=20)),
                ('pce', models.CharField(default='', max_length=20)),
                ('clasificacion_pt', models.CharField(default='', max_length=50)),
                ('clasificacion_te', models.CharField(default='', max_length=50)),
                ('clasificacion_pce', models.CharField(default='', max_length=50)),
                ('ganancia_peso_gr', models.FloatField(default=0)),
                ('calorias_1g_tejido', models.FloatField(default=0)),
                ('calorias_crecimiento', models.FloatField(default=0)),
                ('veces_que_gane', models.IntegerField(default=1)),
                ('ajuste_deficit', models.FloatField(default=0)),
                ('kcal_totales', models.FloatField(default=0)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ninoinfo')),
            ],
        ),
    ]
