# Generated by Django 4.2.7 on 2024-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_ninosanoinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninoinfo',
            old_name='estatura',
            new_name='ajuste_deficit',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='gimnasio',
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='alimentacion',
            field=models.CharField(default='No Aplica', max_length=50),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='calorias_crecimiento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='clasificacion_pce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='clasificacion_pt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='clasificacion_te',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='kcal_totales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='pce',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='pt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='te',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='perimetro_cefalico',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='talla',
            field=models.FloatField(),
        ),
    ]
