# Generated by Django 4.2.7 on 2024-09-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_rename_estatura_ninoinfo_ajuste_deficit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninoinfo',
            old_name='ajuste_deficit',
            new_name='estatura',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='alimentacion',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='calorias_crecimiento',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='clasificacion_pce',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='clasificacion_pt',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='clasificacion_te',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='kcal_totales',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='pce',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='pt',
        ),
        migrations.RemoveField(
            model_name='ninoinfo',
            name='te',
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='perimetro_cefalico',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='sexo',
            field=models.CharField(default='No especificado', max_length=10),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='talla',
            field=models.FloatField(default=0.0),
        ),
    ]
