# Generated by Django 4.2.7 on 2024-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_ninosanoinfo_formula_infantil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lactanteinfo',
            name='descripcion_actividad_fisica',
            field=models.CharField(default='Ligero', max_length=50),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='energia_extra_requerida',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='factor_actividad_fisica',
            field=models.FloatField(default=1.4),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='requerimiento_energia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='requerimiento_energia_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='tasa_metabolica',
            field=models.FloatField(default=0),
        ),
    ]
