# Generated by Django 4.2.7 on 2024-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_lactanteinfo_descripcion_actividad_fisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lactanteinfo',
            name='retencion_post_parto_detalle',
            field=models.FloatField(default=0),
        ),
    ]
