# Generated by Django 4.2.7 on 2024-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_lactanteinfo_retencion_post_parto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lactanteinfo',
            name='retencion_post_parto_detalle',
            field=models.CharField(default='No calculado', max_length=50),
        ),
    ]
