# Generated by Django 4.2.7 on 2024-09-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_lactanteinfo_retencion_post_parto_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestanteinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='lactanteinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ninoinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20, unique=True),
        ),
    ]
