# Generated by Django 4.2.7 on 2024-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_gestanteinfo_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestanteinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='lactanteinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AlterField(
            model_name='ninoinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
