# Generated by Django 4.2.7 on 2024-09-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alumno_fecha_creacion_entrenamiento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='estatura',
        ),
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='gimnasio',
        ),
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='gestanteinfo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='seleccion_multiple',
            field=models.CharField(choices=[('bajo_peso', 'Bajo peso'), ('adecuado', 'Adecuado'), ('sobrepeso', 'Sobrepeso'), ('obesidad', 'Obesidad'), ('adolescente', 'Adolescente'), ('gemelar', 'Gemelar')], default='adecuado', max_length=50),
        ),
    ]
