# Generated by Django 4.2.7 on 2024-09-18 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_gestanteinfo_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestanteinfo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='estatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='gimnasio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gimnasio'),
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='identificacion',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='gestanteinfo',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
