# Generated by Django 4.2.7 on 2024-09-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_gestanteinfo_edad_gestanteinfo_estatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajoPesoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc_saludable', models.FloatField(default=0.0)),
                ('peso_pregestacional_saludable', models.FloatField(default=0.0)),
                ('gramos_semana', models.FloatField(default=0.0)),
                ('ganancia_1_trimestre', models.FloatField(default=2.0)),
                ('ganancia_2_y_3_trimestre_gramos', models.FloatField(default=0.0)),
                ('ganancia_2_y_3_trimestre_kg', models.FloatField(default=0.0)),
                ('ganancia_total', models.FloatField(default=0.0)),
                ('peso_total_embarazo', models.FloatField(default=0.0)),
                ('imc_semana_40', models.FloatField(default=0.0)),
                ('ganancia_peso', models.FloatField(default=0.0)),
                ('evaluacion_ganancia_peso', models.CharField(default='Adecuado', max_length=50)),
                ('gramos_semana_programados', models.FloatField(default=0.0)),
                ('semanas_faltantes', models.IntegerField(default=0)),
                ('gramos_por_semana_reprogramado', models.FloatField(default=0.0)),
                ('tasa_metabolica', models.FloatField(default=0.0)),
                ('factor_actividad_fisica', models.FloatField(default=1.4)),
                ('requerimiento_energia_total', models.FloatField(default=0.0)),
                ('metodo1_g_dia', models.FloatField(default=0.0)),
                ('metodo1_kcal', models.FloatField(default=0.0)),
                ('metodo1_amdr', models.FloatField(default=0.0)),
                ('metodo2_g_dia', models.FloatField(default=0.0)),
                ('metodo2_kcal', models.FloatField(default=0.0)),
                ('metodo2_amdr', models.FloatField(default=0.0)),
                ('base_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gestanteinfo')),
            ],
        ),
    ]
