# Generated by Django 4.2.7 on 2024-09-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_bajopesoinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='evaluacion_ganancia_peso',
            new_name='clasificacion_peso',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='ganancia_peso',
            new_name='debio_ganar',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='gramos_por_semana_reprogramado',
            new_name='ganado',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='gramos_semana_programados',
            new_name='ganancia_2_y_3_trimestre_parte2',
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='ganancia_peso_embarazo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='gramos_por_semana',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='imc_semana_40_parte2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='peso_a_ganar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='peso_total_parte2',
            field=models.FloatField(default=0.0),
        ),
    ]
