# Generated by Django 4.2.7 on 2024-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_rename_evaluacion_ganancia_peso_bajopesoinfo_clasificacion_peso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='ganado',
            new_name='adicion_gestante',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='clasificacion_peso',
            new_name='clasificacion_gramos',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='ganancia_2_y_3_trimestre_parte2',
            new_name='ganancia_2y3_trimestre_gsem',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='ganancia_total',
            new_name='ganancia_primer_trimestre',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='imc_semana_40_parte2',
            new_name='gano',
        ),
        migrations.RenameField(
            model_name='bajopesoinfo',
            old_name='peso_total_parte2',
            new_name='peso_final',
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='ganancia_peso_clasificacion',
            field=models.CharField(default='Adecuado', max_length=50),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='ganancia_tipo',
            field=models.CharField(default='g/sem', max_length=50),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='peso_total_embarazo_titulo_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bajopesoinfo',
            name='total_energia_adicion',
            field=models.FloatField(default=0.0),
        ),
    ]
