# Generated by Django 4.2.7 on 2024-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_sobrepesoinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobrepesoinfo',
            old_name='ganancia_2_y_3_trimestre_parte2',
            new_name='ganancia_2y3_trimestre_gsem',
        ),
        migrations.RenameField(
            model_name='sobrepesoinfo',
            old_name='imc_semana_40_parte2',
            new_name='imc_semana_40_titulo_4',
        ),
        migrations.RenameField(
            model_name='sobrepesoinfo',
            old_name='peso_total_parte2',
            new_name='peso_total_embarazo_titulo_4',
        ),
        migrations.AddField(
            model_name='sobrepesoinfo',
            name='ganancia_peso_clasificacion',
            field=models.CharField(default='Adecuado', max_length=50),
        ),
        migrations.AddField(
            model_name='sobrepesoinfo',
            name='ganancia_primer_trimestre',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='sobrepesoinfo',
            name='total_energia_adicion',
            field=models.FloatField(default=0.0),
        ),
    ]
